#
# Autogenerated by Frugal Compiler (1.3.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#



from thrift.Thrift import TApplicationException
from thrift.Thrift import TMessageType
from thrift.Thrift import TType
from tornado import gen
from frugal.subscription import FSubscription

from valid.ttypes import *




class blahSubscriber(object):

    _DELIMITER = '.'

    def __init__(self, provider):
        """
        Create a new blahSubscriber.

        Args:
            provider: FScopeProvider
        """

        self._transport, self._protocol_factory = provider.new()

    @gen.coroutine
    def subscribe_DoStuff(self, DoStuff_handler):
        """
            DoStuff_handler: function which takes Thing
        """

        op = 'DoStuff'
        prefix = ''
        topic = '%sblah%s%s' % (prefix, self._DELIMITER, op)

        yield self._transport.subscribe(topic, self._recv_DoStuff(self._protocol_factory, op, DoStuff_handler)

    def recv_DoStuff(self, protocol_factory, op, handler):
        def callback(transport):
            iprot = protocol_factory.get_protocol(transport)
            ctx = iprot.read_request_headers()
            mname, _, _ = iprot.readMessageBegin()
            if mname != op:
                iprot.skip(TType.STRUCT)
                iprot.readMessageEnd()
                raise TApplicationException(TApplicationException.UNKNOWN_METHOD)
            req = Thing()
            req.read(iprot)
            iprot.readMessageEnd()
            handler(ctx, req)
        return callback




