#
# Autogenerated by Frugal Compiler (1.3.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#



from thrift.Thrift import TApplicationException
from thrift.Thrift import TMessageType
from thrift.Thrift import TType
from tornado import gen
from frugal.subscription import FSubscription

from valid.ttypes import *




class FooPublisher(object):
    """
    And this is a scope docstring.
    """

    _DELIMITER = '.'

    def __init__(self, provider):
        """
        Create a new FooPublisher.

        Args:
            provider: FScopeProvider
        """

        self._transport, protocol_factory = provider.new()
        self._protocol = protocol_factory.get_protocol(self._transport)

    @gen.coroutine
    def open(self):
        yield self._transport.open()

    @gen.coroutine
    def close(self):
        yield self._transport.close()

    def publish_Foo(self, ctx, baz, req):
        """
        This is an operation docstring.
        
        Args:
            ctx: FContext
            baz: string
            req: Thing
        """

        op = 'Foo'
        prefix = 'foo.bar.%s.qux.' % (baz)
        topic = '%sFoo%s%s' % (prefix, self._DELIMITER, op)
        oprot = self._protocol
        self._transport.lock_topic(topic)
        try:
            oprot.write_request_headers(ctx)
            oprot.writeMessageBegin(op, TMessageType.CALL, 0)
            req.write(oprot)
            oprot.writeMessageEnd()
            oprot.get_transport().flush()
        finally:
            self._transport.unlock_topic()


    def publish_Bar(self, ctx, baz, req):
        """
        Args:
            ctx: FContext
            baz: string
            req: Stuff
        """

        op = 'Bar'
        prefix = 'foo.bar.%s.qux.' % (baz)
        topic = '%sFoo%s%s' % (prefix, self._DELIMITER, op)
        oprot = self._protocol
        self._transport.lock_topic(topic)
        try:
            oprot.write_request_headers(ctx)
            oprot.writeMessageBegin(op, TMessageType.CALL, 0)
            req.write(oprot)
            oprot.writeMessageEnd()
            oprot.get_transport().flush()
        finally:
            self._transport.unlock_topic()

