#
# Autogenerated by Frugal Compiler (1.9.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException
from f_types import *

const_i32_from_base = 582
