version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/lib/go"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    reviewers:
      - "Workiva/service-platform"
    commit-message:
      prefix: "go-lib: "
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    reviewers:
      - "Workiva/service-platform"
    commit-message:
      prefix: "go-tool: "
  - package-ecosystem: "maven"
    ignore:
      # Ignore all semver major upgrades
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
    directory: "/lib/java"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    reviewers:
      - "Workiva/service-platform"
    commit-message:
      prefix: "java-lib: "
  - package-ecosystem: "maven"
    ignore:
      # Ignore all semver major upgrades
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
    directory: "/examples/java"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    reviewers:
      - "Workiva/service-platform"
    commit-message:
      prefix: "java-exam: "
  - package-ecosystem: "gomod"
    directory: "/examples/go"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    reviewers:
      - "Workiva/service-platform"
    commit-message:
      prefix: "go-exam: "
  - package-ecosystem: "maven"
    ignore:
      # Ignore all semver major upgrades
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
    directory: "/test/integration/java/frugal-integration-test"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    reviewers:
      - "Workiva/service-platform"
    commit-message:
      prefix: "java-test: "
  - package-ecosystem: "gomod"
    directory: "/test/integration"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    reviewers:
      - "Workiva/service-platform"
    commit-message:
      prefix: "go-test: "
  - package-ecosystem: "pip"
    directory: "/lib/python"
    schedule:
      interval: "weekly"
    ignore:
      # ignore all updates for version python2 libraries
      - dependency-name: "coverage"
        versions: [ "5.6b1", "5.5b1" ]
      - dependency-name: "mock"
        versions: [ "3.0.5", "3.0.0"]
    target-branch: "develop"
    reviewers:
      - "Workiva/service-platform"
    commit-message:
      prefix: "py-lib: "
