this yaml inherits bot from team, do not add bot

codecov:
  url: "https://codecov.workiva.net"

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: no
    patch: no
  flags:
    dart_library: Dart Library
      paths:
        - lib/dart/lib/src
    go_library: Golang Library
      paths:
        - lib/go

    python_two: Python 2 Libraries (Tornado, GAE)
      paths:
        - lib/python/unit_tests_py2.xml
    python_three: Python 3 Libraries (Asyncio)
      paths:
        - lib/python/unit_tests_py3.xml

comment:
  layout: header, diff, changes, sunburst, uncovered, tree
  behavior: default