#this yaml inherits bot from team, do not add bot

codecov:
  url: "https://codecov.workiva.net"
  branch: master

coverage:

  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      dart_library:
        enabled: yes
        flags: dart_library
      java_library:
        enabled: yes
        flags: java_library
      go_library:
        enabled: yes
        flags: go_library
#      python_two:
#        enabled: yes
#        flags: python_two
    patch: no


comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  behavior: default
#  flags:
#    - dart_library
#    - go_library
#    - java_library


  #  flags:
#    dart_library: Dart Library
#      - lib/dart/
#
#    go_library: Golang Library
#      paths:
#        - lib/go
#
#
#     java_library: Java Library
#      paths:
#        - lib/java
#
#    python_two: Python 2 Libraries (Tornado, GAE)
#      paths:
#        - lib/python
#
#    python_three: Python 3 Libraries (Asyncio)
#      paths:
#        - lib/python/unit_tests_py3.xml