this yaml inherits bot from team, do not add bot

codecov:
  url: "https://codecov.workiva.net"

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: no
    patch: no
  flags:
    - dart_library
    - go_library

comment:
  layout: header, diff, changes, sunburst, uncovered, tree
  behavior: default