#
# Autogenerated by Frugal Compiler (1.9.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException
import base.f_types


from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
    from thrift.protocol import fastbinary
except:
    fastbinary = None


class HealthCondition:
    PASS = 1
    WARN = 2
    FAIL = 3
    UNKNOWN = 4

    _VALUES_TO_NAMES = {
        1: "PASS",
        2: "WARN",
        3: "FAIL",
        4: "UNKNOWN",
    }

    _NAMES_TO_VALUES = {
        "PASS": 1,
        "WARN": 2,
        "FAIL": 3,
        "UNKNOWN": 4,
    }

class ItsAnEnum:
    FIRST = 2
    SECOND = 3
    THIRD = 4

    _VALUES_TO_NAMES = {
        2: "FIRST",
        3: "SECOND",
        4: "THIRD",
    }

    _NAMES_TO_VALUES = {
        "FIRST": 2,
        "SECOND": 3,
        "THIRD": 4,
    }

