name: client_example
version: 0.0.1

environment:
  sdk: ^1.12.0

dependencies:
  logging: ^0.11.2
  event:
    path: ../gen-dart/event
  frugal:
    hosted:
      name: frugal
      url: https://pub.workiva.org
    version: ^1.1.0
  thrift:
    hosted:
      name: thrift
      url: https://pub.workiva.org
    version: ^0.0.5

