name: Compiler
on: push

permissions:
  contents: read
  id-token: write

jobs:
  cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Check
        run: go vet ./...

      - name: Test
        run: go test ./... --race