name: Compiler
on: push

permissions:
  contents: read
  id-token: write

jobs:
  cli:
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:

      - name: Check
        run: make check-cli

      - name: Test
        run: make unit-cli