name: Integration
on:
  workflow_call: {}

permissions:
  pull-requests: write
  contents: write
  id-token: write
  checks: write

jobs:
  Integration:
    name: 🧪 Integration Test
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Credentials
        uses: Workiva/gha-setup-credentials@v1.0.25

      - name: Install Frugal binary
        run: go install

      # TODO because base image change, these brokers need to be installed another way
      - name: Start Brokers
        run: |
          nats-server &
          /opt/activemq/bin/activemq start

      - name: Generate integration files from IDL
        run: ./scripts/integration/generate.sh

      - name: Run setup in parallel
        run: |
          mkdir -p testing/artifacts
          go get github.com/sirupsen/logrus
          go run scripts/skynet/cross/cross_setup.go

      - name: Run tests
        run: |
          cd test/integration
          go run main.go --tests tests.json --outDir "testing/artifacts/cross-runner.log"

      - name: Upload Logs
        uses: workiva/gha-store-artifacts@v1.1.1
        if: always()    # run this step even if previous step failed
        with:
          NON_DEPLOYABLE: "INTEGRATION_TEST_LOGS: testing/artifacts/*"

      - name: Upload Test Artifacts
        uses: Workiva/gha-upload-test-reports@v1.0.13