name: Libraries
on: push

permissions:
  contents: read
  id-token: write

env:
  GOLANG_VERSION: "1.20"
  DART_VERSION: "2.19.6"

jobs:
  dart:
    name: Dart
    timeout-minutes: 20
    runs-on: [self-hosted, small]
    defaults:
      run:
        working-directory: lib/dart
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Credentials
        uses: Workiva/gha-setup-credentials@v1.0.25

      - uses: dart-lang/setup-dart@v1.6.0
        with:
          sdk: ${{ env.DART_VERSION }}

      - name: Install Dart dependencies
        uses: Workiva/gha-dart/pub-get@v0.5.6
        with:
          package-path: .

      - name: Test
        run: |
          dart test
          dart format --set-exit-if-changed -o none lib test

      - name: Package library
        run: tar -czf frugal.pub.tgz .

      - name: Publish artifacts
        uses: Workiva/gha-store-artifacts@v1.1.1
        with:
          PUB: frugal.pub.tgz

      - name: Upload Test Artifacts
        uses: Workiva/gha-upload-test-reports@v1.0.13

  java:
    name: Java
    timeout-minutes: 20
    runs-on: [self-hosted, small]
    defaults:
      run:
        working-directory: lib/java
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Credentials
        uses: Workiva/gha-setup-credentials@v1.0.25

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'

      - name: Test
        run: |
          mvn checkstyle:checkstyle
          mvn verify -q -Dcheckstyle.skip

      - name: Package library
        run: mv $(find target -type f -name 'frugal-*.*.*.jar' | grep -v javadoc) .


      - name: Publish artifacts
        uses: Workiva/gha-store-artifacts@v1.1.1
        with:
          JAVA: frugal-*.*.*.jar

      - name: Upload Test Artifacts
        uses: Workiva/gha-upload-test-reports@v1.0.13

  go:
    name: Go
    timeout-minutes: 20
    runs-on: [self-hosted, small]
    defaults:
      run:
        working-directory: lib/go
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Credentials
        uses: Workiva/gha-setup-credentials@v1.0.25

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      - name: Test
        run: |
          go mod tidy
          go vet
          go test -v -race

      - name: Upload Test Artifacts
        uses: Workiva/gha-upload-test-reports@v1.0.13

  python-2:
    name: Python 2
    timeout-minutes: 20
    runs-on: [self-hosted, small]
    defaults:
      run:
        working-directory: lib/python
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Credentials
        uses: Workiva/gha-setup-credentials@v1.0.25

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '2.7'
          cache: 'pip'

      - name: Test
        run: |
          pip install --upgrade pip
          pip install -Ur
            ../python2/requirements_python_2.txt \
            requirements_python_3.txt \
            requirements_dev_gae.txt \
            requirements_dev_tornado.txt
          flake8 --exclude=tests,frugal/tornado
          nosetests \
            --exclude-dir=frugal/tornado \
            --exclude-dir=frugal/tests/tornado \
            --exclude-dir=frugal/gae \
            --exclude-dir=frugal/tests/gae \
            --exclude-dir=frugal/aio \
            --logging-level=ERROR

      - name: Package library
        run: python setup.py sdist

      - name: Publish artifacts
        uses: Workiva/gha-store-artifacts@v1.1.1
        with:
          PYPI: dist/frugal-*.tar.gz

      - name: Upload Test Artifacts
        uses: Workiva/gha-upload-test-reports@v1.0.13

  python:
    name: Python
    timeout-minutes: 20
    runs-on: [self-hosted, small]
    defaults:
      run:
        working-directory: lib/python
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Credentials
        uses: Workiva/gha-setup-credentials@v1.0.25

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'

      - name: Test
        run: |
          pip install --upgrade pip
          pip install -Ur \
            requirements_python_3.txt \
            requirements_dev_gae.txt \
            requirements_dev_tornado.txt
          flake8 --exclude=tests,frugal/tornado
          nosetests \
            --exclude-dir=frugal/tornado \
            --exclude-dir=frugal/tests/tornado \
            --exclude-dir=frugal/gae \
            --exclude-dir=frugal/tests/gae \
            --exclude-dir=frugal/aio \
            --logging-level=ERROR

      - name: Package library
        run: python setup.py sdist

      - name: Publish artifacts
        uses: Workiva/gha-store-artifacts@v1.1.1
        with:
          PYPI: dist/frugal-*.tar.gz

      - name: Upload Test Artifacts
        uses: Workiva/gha-upload-test-reports@v1.0.13

  # TODO enable this when building works
  # call-integration-test:
  #   name: 🧪 Integration Test
  #   needs:
  #       - dart
  #       - go
  #       - java
  #       - python
  #   uses: ./.github/workflows/integration.yaml
