name: CI for Frugal Libraries
on: push

permissions:
  contents: read
  id-token: write

jobs:
  lib-go:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lib/go

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.4'

      - name: Test
        run: go test -v -race

  lib-java:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lib/java
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'

      - name: Verify
        run: mvn --batch-mode --update-snapshots clean verify -q

  lib-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    defaults:
      run:
        working-directory: lib/python
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements_python_3.txt ]; then pip install -r requirements_python_3.txt; fi

      - name: Lint
        run: flake8 --exclude=tests,frugal/tornado

      - name: Test
        run: nosetests --exclude-dir=frugal/tornado --exclude-dir=frugal/tests/tornado --exclude-dir=frugal/gae --exclude-dir=frugal/tests/gae --logging-level=ERROR
