name: CI for Frugal Libraries
on: push

permissions:
  contents: read
  id-token: write

jobs:
  lib-go:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lib/go
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.4'

      - name: Test
        working-directory: ./lib/go
        run: go test -v -race
