name: "Build"
on:
  pull_request:
    branches:
      - "develop"
  push:
    branches:
      - "master"
      - "develop"
      - "qa/*"
    tags:
      - "*"

permissions:
  pull-requests: write
  contents: write
  id-token: write
  checks: write

env:
  GOLANG_VERSION: "1.20"

jobs:
  build:
    name: Build Go
    timeout-minutes: 20
    runs-on: [self-hosted, small]
    container:
      image: drydock-prod.workiva.net/workiva/messaging-docker-images:0.1.16
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Credentials
        uses: Workiva/gha-setup-credentials@v1.0.25

      - name: Unit tests in parallel
        run: |
          pushd lib/go
          GO111MODULE=on go mod vendor
          go get github.com/sirupsen/logrus
          go test -race -coverprofile=../../gocoverage.txt
          popd 
          tar -czf goLib.tar.gz ./lib/go

      - name: Upload coverage
        uses: workiva/gha-store-artifacts@v1.1.1
        if: always()    # run this step even if previous step failed
        with:
          NON_DEPLOYABLE: "GO_TEST_COVERAGE: gocoverage.txt"

      - name: Upload coverage
        uses: workiva/gha-store-artifacts@v1.1.1
        if: always()    # run this step even if previous step failed
        with:
          NON_DEPLOYABLE: "BUILD_ARTIFACTS_GO_LIBRARY: goLib.tar.gz"

      - name: Upload Test Artifacts
        uses: Workiva/gha-upload-test-reports@v1.0.13


  # TODO enable this when building works
  # call-cross-test-workflow:
  #   name: 🧪 Cross Tests
  #   needs: [build]
  #   uses: ./.github/workflows/cross_test.yaml
